coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 1%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        target: 50%
        threshold: 5%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
  round: down
  precision: 2

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "docs/"
  - "tasks/"
  - "**/__pycache__/"
  - "**/*.pyc"
  - "**/conftest.py"
  - "setup.py"
  - "tests/integration/"
  - "tests/**/test_*"

flags:
  unittests:
    paths:
      - src/github_project_manager_mcp/

# Don't fail on import-only changes
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
